### ISSUE TITLE
Can‘t view texture

### ISSUE THREAD

**Issue by otakudj** [ashawkey/vscode-mesh-viewer#1]
Thank you for the new extension! i have also troubled by can't view textured mesh in vscode when ssh to an remote server, but i still can't view the texture which can be seen in meshlab or blender. 
![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/27484315/ecd34825-a988-41bf-8383-08c795fd4713)
![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/27484315/e7ccb985-c2cf-4771-acdc-73897ca94281)
![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/27484315/0d7bef24-5799-45da-a277-850fd61b8fdf)
Here is the .obj and .mtl file, it's a mesh from shapenet, class: 02691156, uuid: 1a04e3eab45ca15dd86060f189eb133
[models.zip](https://github.com/user-attachments/files/16154940/models.zip)
Is there something wrong on my config or operation? Looking forward for you reply!

**Comment by ashawkey** [comment]
@otakudj Hi, thanks for using it! 
Unfortunately, obj with mtl is not well supported for now. Our viewer only reads the obj file, while the color is defined in the mtl file. Other online mesh viewer (https://threejs.org/editor/) also fails because we cannot upload mtl with obj:
![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/25863658/5edcd41c-6cd2-4b69-9c97-54f5300be243)

**Comment by otakudj** [comment]
Thank you for the instant reply. By the way, can it view single .obj/.ply file with vertex color? I tried a ply file but it still doesn't have color, like this
![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/27484315/7d427093-2419-496f-84ae-99a9edc6d17e)![image](https://github.com/ashawkey/vscode-mesh-viewer/assets/27484315/1795a964-0798-47b2-8b29-452bb1fdc27a)
Here is the .ply file
[0_10.zip](https://github.com/user-attachments/files/16155510/0_10.zip)

**Comment by ashawkey** [comment]
This one also doesn't work in threejs editor or Windows 3D viewer... The only place it works seems to be meshlab. I guess the ply with vertex color is also not well supported. 
To show texture, it's better to use more standard format such as glb.

**Comment by otakudj** [comment]
Got it! Thank you for your reply

**Comment by ubless607** [comment]
Looking forward to this feature too...!
